name: ci

on:
  push:
    paths:
    - "**.py"
    - ".github/workflows/ci.yml"
  pull_request:
    paths:
    - "**.py"

jobs:

  linux:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      matrix:
        python-version: [ '3.7', '3.9' ]
    name: Lint Python ${{ matrix.python-version }}

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - run: pip install .[tests,lint]
    - run: flake8
    - run: mypy
    - run: pytest

  integration:
    needs: linux
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.7'

    - run: pip install .[tests]
    - run: pytest
